version: '3.8'

networks:
  otel-network:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - otel-network

  kafka:
    image: bitnami/kafka:3.4.1
    networks:
      - otel-network
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SSL,EXTERNAL:SSL
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://192.168.122.247:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=kafkacertpass
      - KAFKA_CFG_SSL_KEY_PASSWORD=kafkacertpass
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=kafkacertpass
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    volumes:
      - ./certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:Z
      - ./certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:Z
    ports:
      - "9093:9093"  # Expose the external SSL port

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    networks:
      - otel-network
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
      - ./certs/ca.crt:/etc/otel/certs/ca.crt:Z
      - ./certs/client.crt:/etc/otel/certs/client.crt:Z
      - ./certs/client.key:/etc/otel/certs/client.key:Z
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"  # Expose the OTLP HTTP receiver port

