version: '3.8'

networks:
  otel-network:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - otel-network

  kafka:
    image: bitnami/kafka:3.4.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.122.247:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - otel-network
    healthcheck:
      test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10

  topic-creator:
    image: bitnami/kafka:3.4.1
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - otel-network
    entrypoint:
      - /bin/sh
      - -c
      - |
        while ! /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list 2>/dev/null; do
          echo "Waiting for kafka to be ready..."
          sleep 5
        done
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic otel-messages --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 || echo "Topic 'otel-messages' already exists"
        touch /tmp/healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/healthy"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: "no"

  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      topic-creator:
        condition: service_healthy
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro,Z
    command: ["--config", "/etc/otel-collector-config.yaml"]
    networks:
      - otel-network

