receivers:
  otlp:
    protocols:
      grpc:
      http: 
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  kafka:
    brokers:
      - kafka:9092
    topic: otel-events
    protocol_version: 2.0.0
    encoding: "otlp_json"
    auth:
      tls:
        ca_file: /etc/otel/certs/ca.crt
        cert_file: /etc/otel/certs/client.crt
        key_file: /etc/otel/certs/client.key
        insecure: true
    retry_on_failure:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
