global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx_monitor'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module by default
    static_configs:
      - targets:
        - http://nginx:80  # The URL of the Nginx service
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The Blackbox Exporter address

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9094']

rule_files:
  - '/etc/prometheus/alert.rules.yml'

