- name: Process OpenTelemetry events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: 192.168.122.247
        port: 9093
        topic: otel-events
        group_id: ansible-group
        security_protocol: SSL
        cafile: ./certs/ca.crt
        certfile: ./certs/client.crt
        keyfile: ./certs/client.key
        check_hostname: false

  rules:
    - name: Debug
      condition: event.body != ""
      action:
        debug:
