---
- name: Open Ticket
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Open ServiceNow incident
      servicenow.itsm.incident:
        state: new
        caller: "admin"
        short_description: "{{ title }}"
        description: "{{ description }} at {{ date }}"
        impact: "low"
        urgency: "high"
      register: incident

    - name: Set ServiceNow incident state
      servicenow.itsm.incident:
        state: in_progress
        number: "{{ incident.record.number }}"

    - name: Set ServiceNow incident number
      ansible.builtin.set_stats:
        data:
          incident: "{{ incident.record.number }}"
