---
- name: Parse Kafka Message
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Parse payload
      ansible.builtin.set_fact:
        parsed_payload: "{{ kafka_message.body.resourceLogs[0].scopeLogs[0].logRecords[0].body.stringValue | from_json }}"

    - name: Set facts
      ansible.builtin.set_fact:
        status: "{{ parsed_payload.status }}"
        description: "{{ parsed_payload.annotations.description }}"
        title: "{{ parsed_payload.annotations.summary }}"
        date: "{{ parsed_payload.startsAt }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ status }} {{ description }} {{ title }} {{ date }}"
